server:
  port: 8982
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MSSQLServer
    username: REPLACE_ME
    password:
  jpa:
    hibernate:
      ddl-auto: validate